Учебный проект: хрустящий CRUD
htmlacademy-nodejs/11545-buy-and-sell-3 pull request #9
Opened 2021-09-18 05:39 UTC by johnnypiston

2021-09-18 07:38 UTC, dean992008 requested changes

2021-09-18 07:38 UTC, dean992008 commented on src/service/api/index.js
> +  apiRouter.use(`/category`, getCategoryRouter(new CategoryService(data)));
Этот роут должен быть `/api/categories`

2021-09-18 07:38 UTC, dean992008 commented on src/service/api/offer.js
> +  route.get(`/:offerId/comments`, offerExist(offerService), (req, res) => {
Этот роут возвращяет 404

2021-09-18 07:38 UTC, dean992008 commented on src/service/api/index.js
> +  const data = await getMockData();
Если файла с моками и мы его генерируем получаем ошибку http://joxi.ru/KAgGQ0QSEPpVxA

Нужно чтобы эти данные вызывались в `run` сервера и передавались в этот модуль. Или можно iife заменить на обычную функцию которую вызывать в `run`

2021-09-18 07:38 UTC, dean992008 commented on src/service/api/search.js
> +    const searchStatus = searchResults.length > 0 ? HttpResponseCode.OK : HttpResponseCode.NOT_FOUND;
Если результатов нет то это всеравно 200, но с пустым масивом в результатах.

2021-09-18 07:38 UTC, dean992008 commented on src/service/middlewares/offer-validator.js
> +const offerKeys = [`category`, `description`, `picture`, `title`, `type`, `sum`];
- Нужно добавить вализацию для коментария. 
- Нужно сделать чтобы это модуль принимал поля для валидации из все и использовать этот модуль для вадидации оферов и коментариев.

2021-09-22 15:34 UTC, johnnypiston commented on src/service/api/offer.js
> +  route.get(`/:offerId/comments`, offerExist(offerService), (req, res) => {
Вроде работает, я ничего не менял. Если mock.json сгенерирован и id верный, то все работает. [Скрин запроса](https://user-images.githubusercontent.com/5562598/134373802-91042792-2ae8-47cc-a44d-04f99b399021.png)

2021-09-22 18:33 UTC, dean992008 commented on src/service/api/offer.js
> +  route.get(`/:offerId/comments`, offerExist(offerService), (req, res) => {
Да, так и есть у меня был пробел в url в конце.

2021-09-22 18:33 UTC, merged